### ISSUE TITLE
Not working with PDM 2.5.0b0

### ISSUE THREAD

**Issue by capdevc** [frostming/pdm-vscode#6]
`pdm init -v` with pdm-vscode installed:

```
% pdm init -v
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/local/bin/python3.10 (3.10)
1. /usr/local/bin/python3.9 (3.9)
2. /usr/bin/python3 (3.9)
3. /usr/local/bin/python3.8 (3.8)
4. /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11 (3.11)
Please select (0): 4
Using Python interpreter: /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11 (3.11)
Using __pypackages__ because non-venv Python is used.
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/core.py", line 253, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/core.py", line 186, in main
    command.handle(project, options)
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 55, in handle
    python = actions.do_use(
             ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 659, in do_use
    hooks.try_emit("post_use", python=selected_python)
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm/cli/hooks.py", line 54, in try_emit
    pdm_signals.signal(name).send(self.project, hooks=self, **kwargs)
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/blinker/base.py", line 263, in send
    return [(receiver, receiver(sender, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/blinker/base.py", line 263, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.4.9/libexec/lib/python3.11/site-packages/pdm_vscode/hook.py", line 51, in generate_vscode_settings
    if env.is_global:
       ^^^^^^^^^^^^^
AttributeError: 'PythonLocalEnvironment' object has no attribute 'is_global'. Did you mean: 'is_local'?
```

**Comment by frostming** [comment]
Thanks, this will be resolved in the PDM project.
